apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/prod/istio-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
